# Generated by Django 3.1.4 on 2021-01-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_park'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='address',
            new_name='formatted_address',
        ),
        migrations.AddField(
            model_name='park',
            name='opening_hours',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
