# Generated by Django 3.1.4 on 2021-01-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210112_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='photo',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
