# Generated by Django 3.1.4 on 2021-01-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_park_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='rating',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
